name: reviewdog
on: [pull_request]
jobs:
  lint:
    name: pr/lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Biome with Reviewdog
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Run misspell with Reviewdog
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-pr-review
          pattern: |
            **/*
            !pnpm-lock.yaml
            !*.lock
            !assets/*
          exclude: |
            pnpm-lock.yaml
            *.lock
            assets/*
